### ISSUE TITLE
How to invoke via HTTP api properly ?

### ISSUE THREAD

**Issue by sokoow** [faas-and-furious/inception-function#2]
I got two questions:

1. How to invoke this function through HTTP  ? What do you give it in POST ?
2. I think I found a really interesting bug:

```curl -XPOST -u XXX:YYY https://FAAS-ENDPOINT/function/inception -d "url:https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg"
signal: illegal instruction (core dumped)
```

**Comment by alexellis** [comment]
Hi
You give a URL. This is not for Raspberry Pi or ARM64 though.

Try the function via the OpenFaaS function store. That's the easiest way to consume it. 

Alex

**Comment by burf2000** [comment]
I have the same issue randomly, installed vai the storey
http://192.168.0.100:8080/function/inception?URL=https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg
signal: illegal instruction (core dumped)

if I try vai the Faas portal
Internal Server Error
signal: illegal instruction (core dumped)

**Comment by alexellis** [comment]
HI @burf2000 @sokoow what platforms are you both running on?

I'm going to close this issue and ask you both to fill out this template so that I can help you.

Include the RAM on the nodes please.

BTW: the function works through a HTTP POST of a URL.

Alex

**Comment by alexellis** [comment]
Usage is explained in the README: https://github.com/faas-and-furious/inception-function

If you are running with 1GB or RAM or lower, try a node with 2GB available.

Alex

**Comment by alexellis** [comment]
Derek lock
